Gamegoo-repo/Gamegoo-Server-v2

- src/main/java/com/gamegoo/gamegoo_v2/block/controller/BlockController.java
- src/main/java/com/gamegoo/gamegoo_v2/block/domain/Block.java
- src/main/java/com/gamegoo/gamegoo_v2/block/repository/BlockRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockService.java
- src/main/java/com/gamegoo/gamegoo_v2/common/validator/MemberValidator.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/BlockException.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/ErrorCode.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/MemberException.java
- src/main/java/com/gamegoo/gamegoo_v2/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/member/service/MemberService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/ControllerTestSupport.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockMemberTest.java
- src/test/resources/application.yml
> [Feat/15] 회원 차단 API 구현 및 테스트

- build.gradle
- src/main/java/com/gamegoo/gamegoo_v2/auth/controller/AuthController.java
- src/main/java/com/gamegoo/gamegoo_v2/auth/jwt/JwtProvider.java
- src/main/java/com/gamegoo/gamegoo_v2/block/controller/BlockController.java
- src/main/java/com/gamegoo/gamegoo_v2/block/dto/BlockListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/block/repository/BlockRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockService.java
- src/main/java/com/gamegoo/gamegoo_v2/common/annotation/ValidPage.java
- src/main/java/com/gamegoo/gamegoo_v2/common/annotationValidator/ValidPageAnnotationValidator.java
- src/main/java/com/gamegoo/gamegoo_v2/common/validator/MemberValidator.java
- src/main/java/com/gamegoo/gamegoo_v2/config/SwaggerConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/MemberException.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/ExceptionAdvice.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/MemberException.java
- src/main/java/com/gamegoo/gamegoo_v2/member/service/MemberService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/block/BlockRepositoryTest.java
> 회원 차단 목록 조회 API 구현 및 테스트
```
public ApiResponse<BlockListResponse> getBlockList(@ValidPage @RequestParam(name = "page") Integer page,
@AuthMember Member member)
```
이 어노테이션을 붙이면 파라미터로 받은 page의 값이 1보다 작은 경우 에러를 발생시킵니다
> [Feat/18] 회원 차단 목록 조회 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/block/controller/BlockController.java
- src/main/java/com/gamegoo/gamegoo_v2/block/domain/Block.java
- src/main/java/com/gamegoo/gamegoo_v2/block/repository/BlockRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
> [Feat/20] 회원 차단 해제 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/block/controller/BlockController.java
- src/main/java/com/gamegoo/gamegoo_v2/block/domain/Block.java
- src/main/java/com/gamegoo/gamegoo_v2/block/repository/BlockRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/block/BlockRepositoryTest.java
> [Feat/22] 차단 목록 삭제 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/friend/controller/FriendController.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
> [Feat/29] 친구 요청 거절 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/common/validator/FriendValidator.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/controller/FriendController.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/domain/Friend.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/dto/StarFriendResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
> [Feat/33] 친구 즐겨찾기 설정/해제 API 구현 및 테스트

- .github/workflows/pr_test.yml
- .gitignore
- build.gradle
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockService.java
- src/main/java/com/gamegoo/gamegoo_v2/common/annotation/ValidCursor.java
- src/main/java/com/gamegoo/gamegoo_v2/common/annotationValidator/ValidCursorAnnotationValidator.java
- src/main/java/com/gamegoo/gamegoo_v2/config/QuerydslConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/ExceptionAdvice.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/controller/FriendController.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/dto/FriendListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendQueryServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/block/BlockRepositoryTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/friend/FriendRepositoryTest.java
> [Feat/39] 친구 목록 조회 API 구현 및 테스트

- build.gradle
- src/main/java/com/gamegoo/gamegoo_v2/config/AsyncConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/event/AcceptFriendRequestEvent.java
- src/main/java/com/gamegoo/gamegoo_v2/event/FriendRequestEvent.java
- src/main/java/com/gamegoo/gamegoo_v2/event/RejectFriendRequestEvent.java
- src/main/java/com/gamegoo/gamegoo_v2/event/SendFriendRequestEvent.java
- src/main/java/com/gamegoo/gamegoo_v2/event/listener/FriendRequestEventListener.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/NotificationException.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/ErrorCode.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
- src/main/java/com/gamegoo/gamegoo_v2/manner/domain/MannerKeyword.java
- src/main/java/com/gamegoo/gamegoo_v2/manner/repository/MannerKeywordRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/domain/Notification.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/domain/NotificationType.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/domain/NotificationTypeTitle.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationTypeRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockQueryFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/notification/NotificationServiceTest.java
> [Feat/41] 알림 생성 이벤트 및 리스너 구현

- src/main/java/com/gamegoo/gamegoo_v2/block/dto/BlockListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/block/service/BlockService.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/controller/NotificationController.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/domain/NotificationType.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/domain/NotificationTypeTitle.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/dto/NotificationCursorListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/dto/NotificationPageListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/dto/NotificationResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/notification/NotificationControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/notification/NotificationFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/notification/NotificationRepositoryTest.java
> [Feat/57] 알림 전체/팝업 목록 조회 API 구현 및 테스트

- .github/workflows/github_actions.yml
- Dockerfile
- build.gradle
- src/main/java/com/gamegoo/gamegoo_v2/auth/dto/JoinRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/auth/service/AuthFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/auth/service/AuthService.java
- src/main/java/com/gamegoo/gamegoo_v2/config/AppConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/config/WebConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/RiotException.java
- src/main/java/com/gamegoo/gamegoo_v2/exception/common/ErrorCode.java
- src/main/java/com/gamegoo/gamegoo_v2/member/controller/MemberController.java
- src/main/java/com/gamegoo/gamegoo_v2/member/service/MemberFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/member/service/MemberService.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/controller/RiotController.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/dto/RiotAccountResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/dto/RiotSummonerResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/dto/RiotVerifyExistUserRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotAccountService.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotInfoService.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotRecordService.java
- src/main/java/com/gamegoo/gamegoo_v2/riot/service/RiotService.java
- src/main/java/com/gamegoo/gamegoo_v2/utils/PasswordUtil.java
- src/main/resources/application.yml
- src/test/resources/application.yml
> [Feat/53] Riot 계정 존재하는지 검증하는 API

- src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/domain/Chat.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/chat/ChatRepositoryTest.java
> [Feat/84] 특정 채팅방의 메시지 내역 조회 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/domain/Chatroom.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/dto/ChatResponseFactory.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/dto/response/ChatroomListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/dto/response/ChatroomResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
- src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockService.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRequestRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/block/BlockRepositoryTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/chat/ChatRepositoryTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/chat/MemberChatroomRepositoryTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/friend/FriendRepositoryTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/friend/FriendServiceTest.java
> 채팅방 목록 조회 API 구현 및 테스트
상대 회원 조회
채팅방 엔티티 조회
가장 마지막 채팅 메시지 조회
안읽은 메시지 개수 조회
상대 회원과의 친구 여부 조회
상대 회원에게 차단 당했는지 여부 조회
두 회원 사이 친구 요청 보낸 회원의 id 조회
이렇게 쿼리를 각각 실행하다보니 채팅방 목록 조회 요청 한 번 당 거의 8~90번의 쿼리가 실행되고 있었더라구요..
이걸 v2에서는 배치 조회로 각각 딱 한 번의 쿼리로 조회해오고 Map에 저장 -> Map에서 값을 뽑아서 dto 생성하도록 변경했습니다. 이렇게 하니까 이제는 쿼리를 7번만 실행하고 있습니다.
> [Feat/104] 채팅방 목록 조회 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/controller/NotificationController.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
> [Feat/116] 매칭을 통한 채팅방 시작 메소드 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/core/common/annotation/NotDuplicated.java
- src/main/java/com/gamegoo/gamegoo_v2/core/common/annotationValidator/NotDuplicatedAnnotationValidator.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/request/MannerInsertRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
> [Feat/138] 비매너 평가 등록 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerKeywordResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/repository/manner/MannerRepositoryTest.java
> [Feat/149] 매너 정보 조회 API 구현 및 테스트

- src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/ReportRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/EmailEventListener.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java
> [Fix/165] 신고 등록 시 관리자 메일 발송 버그 수정

- src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerKeywordListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
> [Feat/163] 매너 정보 및 매너 키워드 개수 조회 API 분리

- src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/core/batch/BatchFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/batch/BatchService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SchedulerConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/core/scheduler/MannerScheduler.java
- src/main/java/com/gamegoo/gamegoo_v2/scheduler/MannerScheduler.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerService.java
- src/main/resources/application.yml
- src/test/java/com/gamegoo/gamegoo_v2/integration/batch/BatchFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/batch/BatchServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/manner/MannerServiceTest.java
- src/test/resources/application.yml
> [Feat/158] 회원 매너 랭크 업데이트 스케줄러 구현 및 테스트

- build.gradle
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthFilter.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityJwtProperties.java
- src/main/resources/application.yml
- src/main/resources/excluded-paths.yml
- src/test/java/com/gamegoo/gamegoo_v2/controller/ControllerTestSupport.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockAdmin.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockAdminSecurityContextFactory.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockMember.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockMemberSecurityContextFactory.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/internal/InternalControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/notification/NotificationControllerTest.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java
> 여기에 작성해주세요.
```
private final CustomAccessDeniedHandler accessDeniedHandler = new CustomAccessDeniedHandler();
```
> [Test/169] 시큐리티 도입으로 인한 테스트코드 수정 및 SecurityConfig 리팩토링

- .github/workflows/github_actions.yml
- Dockerfile
> [Cicd/172] 서버 timezone KST로 설정

- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> [Feat/161] 내가 작성한 게시판 글 목록 조회 API

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthenticationExceptionHandler.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/SecurityUtil.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/core/log/LogUtil.java
- src/main/java/com/gamegoo/gamegoo_v2/core/log/LoggingFilter.java
- src/test/java/com/gamegoo/gamegoo_v2/controller/ControllerTestSupport.java
> [Feat/175] API 요청 LoggingFilter 구현

- .github/workflows/github_actions.yml
- src/main/resources/logback-spring.xml
> 로그 파일 일별 저장 설정
```
- name: 기존 Docker 이미지 삭제
run: docker image prune -a
```
이걸 github_actions.yml에 추가했는데 그래도 기존 이미지 삭제가  안되더라구요 ㅠㅠ 어떻게 해야하는지 아시는 분 계신가요..
> [Feat/178] 로그 파일 일별 저장 설정

- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardBumpResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
> 내가 올린 게시물을 게시판 상단으로 끌어올리는 기능입니다.
> [Feat/190] 끌올 기능 API 구현

- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
> 게시판에서 게시물이 어떻게 보이는지에 대한 수정입니다.
> [Feat/192] 게시판 목록에서 메모, 끌올 시간 불러오기

- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> [Feat/200] 게시판 자유랭크 반영, 자유랭크 기반 게시물 조회

- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
> 게시물 조회 시 티어 파라미터를 2개를 요구해 혼동 야기
> [Fix/214] 게시물 조회 시 티어 파라미터 통합

- src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingStrategyProcessor.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
> 빠른대전 우선순위 계산할 때 티어 반영 안하도록 수정
> [Feat/211] 매칭 빠른대전 티어 기획 수정 반영

- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustom.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
> 매칭 리스트 조회 시 중복 Id 조회되는 문제 해결 + 프로필 조회 수정
> [Fix/222] 매칭 리스트 조회 시 중복 Id 조회되는 문제 해결 + 프로필 조회 수정

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/exception/RiotException.java
- src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
- src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/GlobalException.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotAuthService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotInfoService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
- src/main/java/com/gamegoo/gamegoo_v2/utils/ChampionIdStore.java
- src/main/java/com/gamegoo/gamegoo_v2/utils/EmailTemplateProcessor.java
- src/main/java/com/gamegoo/gamegoo_v2/utils/RiotApiHelper.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
> Riot : 예외처리 추가
> Champion : 모든 경우에도 다 챔피언이 오도록 변경
> Auth : 소환사명 검증 추가
-> Champion 관련 에러응답 전부 삭제
> [Fix/237] Riot, Champion, Auth 에러 해결

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberChampion.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberChampionRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/domain/ChampionStats.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/RiotMatchResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
- src/main/java/com/gamegoo/gamegoo_v2/game/dto/response/ChampionResponse.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
> [Feat/239] 최근 선호 챔피언의 승률, 게임 수 제공

- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingStrategyProcessor.java
- src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
> 정밀 매칭 점수 변경
- 빠른 대전 : 25 - 매너점수 차이
매너레벨(16점) + 포지션(6점) + 마이크 (3점)
- 개인 랭크 : 67 - 매너점수 차이
매너레벨(16점) + 티어(40점) + 포지션(6점) + 마이크 (5점)
- 자유 랭크 : 65점 - 매너점수 차이
매너레벨(16점) + 티어(40점) + 포지션(6점) + 마이크 (3점)
- 칼바람 : 19 - 매너점수 차이
매너레벨(16점) + 마이크 (3점)
> :bug: [Fix] 정밀 매칭 점수 변경

- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
> [Feat/251] 게시글 목록 조회 API 응답에 챔피언 통계 정보 추가

- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
> 게시글 상세 조회 API 응답에 챔피언 통계 정보를 추가하여 사용자의 챔피언 숙련도를 더 상세하게 표시합니다.
> [Feat/249] 회원전용 게시글 상세 조회 API 응답에 챔피언 통계 정보 추가

- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/OAuthRedirectBuilder.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
>RSO 로그인 시 닉네임(name), 프로필 이미지 번호(profileImage), 유저 ID(id)를 프론트로 전달하도록 리다이렉트 URL 개선
미터에 name, profileImage, id 포함되도록 변경
> [Feat/275] RSO 로그인 닉네임, id, 프로필 이미지 번호 추가

- src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailAsyncService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/EmailEventListener.java
> [Fix/297] 신고 등록 시 관리자 메일 전송 버그 수정

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/domain/RefreshToken.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
> refreshToken 동시성 에러 해결
로그 : https://www.notion.so/2145d32b00ae805691ece2b97b45f2ea?source=copy_link
> [Fix/303] Refresh Token 에러 해결

- src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
- src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
> matching found API 호출 시, sender와 receiver의 matchingUuid가 같을 경우 예외처리
> [Feat/309] matching found 예외처리

- src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
> matching free/solo tier,rank 전부 보이도록 수정
> [Feat/314] matching free/solo tier,rank 전부 보이도록 수정

- src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/response/RiotMatchResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
- src/test/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordServiceTest.java
> 최근 전적 챔피언 4개까지 불러오기 && 챔피언 부족 시 추가 조회 x
> [Feat/326] 라이엇 챔피언 db 기획 수정 사항 반영

- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/ChampionStatsRefreshService.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
> [Fix/335] 영속성 문제 해결

- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberChampion.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberRecentStats.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MemberRecentStatsResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/ChampionStatsRefreshService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/ChampionStatsResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/domain/ChampionStats.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/response/RiotMatchResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
- src/test/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MemberRecentStatsResponseTest.java
- src/test/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
> [Feat/339] 라이엇 챔피언 정보 관련 수정 및 추가

- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/ChampionStatsRefreshService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/member/ChampionStatsRefreshServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/member/MemberFacadeServiceRefreshTest.java
> puuid 재사용 및 라이엇 api 호출 실패 시 롤백 처리
> [Fix/348]puuid 재사용 및 라이엇 api 호출 실패 시 롤백 처리

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/response/RiotInfoResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotAuthService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotInfoService.java
> riot API 사용해서 회원가입할 때 발생한 에러 해결
> Riot 측 안내 
> 
> Hey everybody, as a follow up to our last announcement about the endpoints being removed, we are going to be completely removing SummonerIDs and AccountIDs from all endpoint payloads on July 7th, 2025. If your app is dependent on them, please take steps to ensure that you can use PUUIDs moving forward.
> Also, please 
> make sure to use this endpoint for RSO-related summoner requests: /lol/summoner/v4/summoners/me
기존에는 encryptedSummonerId를 사용했지만 보안 정책에 의해 puuid로 변경되었습니다. 해당 변경사항을 반영했습니다.
> [Fix/352] summonerId 사용하는 API 제거

- build.gradle
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberRecentStats.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/P6SpyConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustomImpl.java
- src/main/resources/application.yml
- src/test/java/com/gamegoo/gamegoo_v2/feature/BanFeatureTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/batch/BatchFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/batch/BatchServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/manner/MannerServiceTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
- src/test/java/com/gamegoo/gamegoo_v2/service/report/ReportServiceTest.java
> [Refactor/360] 친구목록 조회 API 쿼리 테스트 및 최적화

- src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/GuestBoardInsertRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
- src/main/resources/excluded-paths.yml
- src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardFacadeServiceTest.java
> 비회원 게시물 등록 로직입니다.
일단 member 관련 데이터 전부 null로 뒀습니다. 
전적 관련 데이터를 어떻게 처리해야할지 고민입니다 ㅎㅎ...
> [Feat/356] 비회원 게시물 등록 로직

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/domain/Role.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
- src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardFacadeServiceTest.java
> 비회원 게시물 라이엇 정보 주입 및 임시 멤버 생성
비회원의 경우 글을 등록할때만 전적을 새로 고침을 하도록 하였습니다!
> [Feat/368] 비회원 게시물 라이엇 정보 주입 및 임시 멤버 생성

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/response/LoginResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/IsMikeRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/PositionRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardUpdateRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/controller/ReportController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/BanRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/ReportProcessRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/ReportRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/ReportSearchRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportProcessResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/OpenApiConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/TierDetails.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/dto/request/InitializingMatchingRequest.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
> openapi 관련 프론트 측 요구 사항으로 shared enum 설정 및 운영 서버의 MemberRecentStats 테이블 데이터 정합성 문제 해결로 optional = false 재추가 입니다.
> [Refactor/381] shared enum 설정 및 optional = false 재추가

- src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
> 신고 목록 조회 및 처리 로직에 비회원 신고 건 반영
> [Fix/386] 신고 목록 조회 및 처리 로직에 비회원 신고 건 반영

- src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepository.java
> 채팅방 목록 조회 Native Query 수정(기존 쿼리는 "안읽은 메시지가 하나도 없는 채팅방"을 채팅방 목록 조회 결과에서 누락하는 잘못된 쿼리 였음)
> [Fix/382] 채팅방 목록 조회 Native Query 수정

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/jwt/JwtProvider.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/CustomUserDetails.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthFilter.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ExceptionAdvice.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
- src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
> JWT 검증 filter에서 DB 조회 로직 제외
기존에는 security filter 단에서 db 조회 로직이 포함되어 있어서 매 요청마다 db 조회를 위해 connection을 가져야했습니다. 이 부분에서 성능 상 병목이 발생해서 db 조회 로직을 제거하고 @AuthMember ArgumentResolver에서 member 엔티티를 조회해올 때 탈퇴 여부도 검증하도록 로직을 수정했습니다.
> [Refactor/392] JWT 검증 filter에서 DB 조회 로직 제외

- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberChampion.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberRecentStats.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MemberRecentStatsResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberChampionRepository.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/ChampionStatsRefreshService.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/domain/ChampionStats.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
- src/test/java/com/gamegoo/gamegoo_v2/service/member/ChampionStatsRefreshServiceTest.java
> 프로필과 마찬 가지로 솔랭 + 자유랭으로 반환하던 정보들을 게시물 성격에 맞춰 반영하도록 작업 했습니다!
> [Feat/397] 라이엇 전적 정보 게시물 반영 시 타입 별 반영

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-qa.yml
- Dockerfile-qa
- src/main/java/com/gamegoo/gamegoo_v2/core/config/CorsProperties.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/test/resources/application.yml
> QA 전용 서버 배포 설정 및 CORS 설정
각 환경별 cicd 스크립트 실행 조건
- prod: main 브랜치에 push 또는 main 브랜치에 pr merge
- dev: develop 브랜치에 pr merge
- qa: qa 브랜치에 push
각 환경별 로그 저장 범위
- prod
- 콘솔 출력
- aws s3 `gamegoo/log/api_server`, `gamegoo/log/socket_server` 경로에 로그 파일 일별 저장
- dev: 콘솔에만 출력
- qa
- 콘솔 출력
- aws s3 `gamegoo/log/qa_api_server`, `gamegoo/log/qa_socket_server` 경로에 로그 파일 일별 저장
> [Ci/399] QA 전용 서버 배포 설정

- src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
- src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/PasswordController.java
- src/main/java/com/gamegoo/gamegoo_v2/account/email/controller/EmailController.java
- src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
- src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatInternalController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
- src/main/java/com/gamegoo/gamegoo_v2/content/report/controller/ReportController.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/OpenApiConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/swagger/ApiErrorCodes.java
- src/main/java/com/gamegoo/gamegoo_v2/core/config/swagger/SwaggerErrorResponseConfig.java
- src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
- src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
- src/main/java/com/gamegoo/gamegoo_v2/notification/controller/NotificationController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/block/controller/BlockController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendInternalController.java
- src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
> Swagger 문서에 백엔드 커스텀 예외 응답이 자동 노출되도록 구성
> [Feat/438] 스웨거 문서 에러코드 관련 추가
