.editorconfig
build.gradle
src/main/java/com/gamegoo/gamegoo_v2/GamegooV2Application.java
src/main/java/com/gamegoo/gamegoo_v2/config/SwaggerConfig.java

> swagger 및 코드 컨벤션 설정
---
---
`'org.springframework.boot:spring-boot-docker-compose'` 
이 의존성 때문에 어플리케이션 실행이 안되어서 의존성 주석 처리했는데 이 부분 꼭 필요한 부분인지 궁금합니다...!
---
---

[Docs/2] swagger 및 코드 컨벤션 설정

---

src/main/java/com/gamegoo/gamegoo_v2/common/validator/BlockValidator.java
src/main/java/com/gamegoo/gamegoo_v2/common/validator/FriendValidator.java
src/main/java/com/gamegoo/gamegoo_v2/exception/FriendException.java
src/main/java/com/gamegoo/gamegoo_v2/exception/common/ErrorCode.java
src/main/java/com/gamegoo/gamegoo_v2/friend/controller/FriendController.java
src/main/java/com/gamegoo/gamegoo_v2/friend/domain/Friend.java
src/main/java/com/gamegoo/gamegoo_v2/friend/domain/FriendRequest.java
src/main/java/com/gamegoo/gamegoo_v2/friend/dto/SendFriendRequestResponse.java
src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepository.java
src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRequestRepository.java
src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
src/main/java/com/gamegoo/gamegoo_v2/member/domain/Member.java
src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java

[Feat/24] 친구 요청 전송 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/friend/controller/FriendController.java
src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java

[Feat/30] 친구 요청 취소 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/email/controller/EmailController.java
src/main/java/com/gamegoo/gamegoo_v2/email/service/EmailFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/email/service/EmailService.java

[Feat/45] 회원용 이메일 인증 API 구현

---

src/main/java/com/gamegoo/gamegoo_v2/email/service/EmailService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/email/EmailFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/email/RandomCodeGeneratorUtilTest.java

[Test/47] 테스트 에러 수정

---

.editorconfig
src/main/java/com/gamegoo/gamegoo_v2/config/WebConfig.java
src/main/java/com/gamegoo/gamegoo_v2/email/controller/EmailController.java
src/main/java/com/gamegoo/gamegoo_v2/email/dto/EmailCodeRequest.java
src/main/java/com/gamegoo/gamegoo_v2/email/repository/EmailVerifyRecordRepository.java
src/main/java/com/gamegoo/gamegoo_v2/email/service/EmailFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/email/service/EmailService.java
src/main/java/com/gamegoo/gamegoo_v2/exception/common/ErrorCode.java

:sparkles:[Feat] 인증 코드 검증 API 구현

---

src/main/java/com/gamegoo/gamegoo_v2/friend/controller/FriendController.java
src/main/java/com/gamegoo/gamegoo_v2/friend/dto/FriendInfoResponse.java
src/main/java/com/gamegoo/gamegoo_v2/friend/dto/FriendListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/friend/repository/FriendRepositoryCustomImpl.java
src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/friend/service/FriendService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendQueryFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/friend/FriendRepositoryTest.java
src/test/java/com/gamegoo/gamegoo_v2/unit/RandomCodeGeneratorUtilTest.java

[Feat/43] 소환사명으로 친구 검색 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/notification/controller/NotificationController.java
src/main/java/com/gamegoo/gamegoo_v2/notification/domain/Notification.java
src/main/java/com/gamegoo/gamegoo_v2/notification/dto/ReadNotificationResponse.java
src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepository.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/notification/NotificationControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendQueryServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/notification/NotificationFacadeServiceTest.java

[Feat/52] 알림 읽음 처리 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/notification/controller/NotificationController.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/notification/NotificationControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/notification/NotificationFacadeServiceTest.java

[Feat/55] 안읽은 알림 개수 조회 API 구현 및 테스트

---

.github/workflows/github_actions.yml

[Feat/34] CICD github_actions 수정

---

.github/workflows/github_actions.yml

> github action 배포 실패 시 디스코드 연동

[CICD/71] github action 배포 실패 시 디스코드 연동

---

.github/workflows/github_actions.yml
src/main/java/com/gamegoo/gamegoo_v2/auth/service/AuthFacadeService.java

:construction_worker: [CICD] Github Action 실패 해결

---

src/main/java/com/gamegoo/gamegoo_v2/game/dto/response/ChampionResponse.java
src/main/java/com/gamegoo/gamegoo_v2/game/dto/response/GameStyleResponse.java
src/main/java/com/gamegoo/gamegoo_v2/member/controller/MemberController.java
src/main/java/com/gamegoo/gamegoo_v2/member/dto/response/MyProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/member/service/MemberFacadeService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/67] 내 프로필 조회 API 구현 및 테스트

---

src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

> Champion Integer로 받았던거 Long으로 받는걸로 수정하다가 생긴 에러 해결하기

[Test/81] 테스트 실패 해결

---

src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Test/85] 다른 회원 조회 API 테스트 코드 작성

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/JoinRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/ProfileImageRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/resources/application.yml
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/87] 프로필 이미지 수정 API

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/IsMikeRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/89] 마이크 여부 수정 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/PositionRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/91] 포지션 변경 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustomImpl.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepositoryCustomImpl.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/ChatValidator.java
src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/chat/ChatRepositoryTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/chat/ChatroomRepositoryTest.java

[Feat/94] 안읽은 채팅방 UUID 조회 API 구현

---

src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepository.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/BaseValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/ChatValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/MemberValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java

[Feat/97] 채팅방 읽음 처리 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/PasswordController.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/PasswordRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/FriendRequestEventListener.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
src/main/resources/application.yml
src/test/java/com/gamegoo/gamegoo_v2/integration/auth/PasswordFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java

> JWT 토큰이 없는 비밀번호 변경하는 API 및 테스트 구현

[Feat/95] 비밀번호 변경 JWT X API 및 테스트 구현

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/PasswordController.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/JoinRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/PasswordCheckRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/PasswordResetRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/PasswordResetWithVerifyRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/response/PasswordCheckResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/auth/PasswordFacadeServiceTest.java

[Feat/103] 비밀번호 확인 API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberGameStyle.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/GameStyleRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberGameStyleRepository.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/108] 게임스타일 수정 API 및 테스트 구현

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/LoginRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/response/LoginResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java

[Feat/111] 로그인 API 및 테스트 구현

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java

[Fix/120] git 충돌 해결

---

src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/BaseValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/BlockValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/ChatValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/FriendValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/MemberValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/FriendRequestEventListener.java
src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/SocketEventListener.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/main/java/com/gamegoo/gamegoo_v2/external/socket/SocketService.java
src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/dto/BlockListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockService.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendService.java

[Refactor/122] javadoc 주석 작성 및 코드 수정

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/RefreshTokenRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/response/RefreshTokenResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/repository/RefreshTokenRepository.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java

[Feat/121] 리프레시 토큰 업데이트 API 및 Test 구현

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/PasswordController.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/email/controller/EmailController.java
src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotAuthService.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotInfoService.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
src/main/java/com/gamegoo/gamegoo_v2/utils/EmailTemplateProcessor.java
src/main/java/com/gamegoo/gamegoo_v2/utils/PasswordUtil.java
src/main/java/com/gamegoo/gamegoo_v2/utils/RandomCodeGeneratorUtil.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[refactor/130] 회원 관련 코드 컨벤션 수정

---

src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatInternalController.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendInternalController.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/controller/internal/InternalControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java

> 친구, 채팅 관련 internal API 구현 및 테스트

[Feat/127] 친구, 채팅 관련 internal API 구현 및 테스트

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/ChampionResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java

[Feat/117] 게시물 목록 조회

---

.github/workflows/github_actions.yml
src/main/java/com/gamegoo/gamegoo_v2/account/auth/jwt/JwtInterceptor.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java

[Fix/135] CORS 에러 수정 

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java

:sparkles: [Feat/134] 회원 전용 게시물 조회

---

src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java

[fix/143] 테스트에서 토큰 검증하기 수정

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java

[Feat/142] 비회원 게시물 조회 API

---

src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/dto/FriendListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustomImpl.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/friend/FriendRepositoryTest.java

[Fix/153] 친구 목록 조회 페이징 로직 제거

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/BoardGameStyle.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardUpdateRequest.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardGameStyleService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java

[Feat/152] 게시물 수정 기능 구현

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java

> 사용자와 게시물 작성자가 동일한지 확인한 후 삭제하는 로직입니다.

[Feat/159] 게시물 삭제 로직

---

src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepositoryCustomImpl.java

[Feat/163] 매너 정보 및 키워드 조회 API 버그 수정

---

.github/workflows/github_actions.yml

[Cicd/172] github_actions.yml 수정

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Position.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/PositionRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

> 포지션 자료형 int -> ENUM으로 변경
- ANY : 아무 챔피언이나 가능
- TOP : 탑
- JUNGLE : 정글
- MID : 미드
- ADC : 원딜
- SUP : 서폿

[Feat/176] 포지션 자료형 int -> ENUM 변경

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardUpdateRequest.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java

> 여기에 작성해주세요.
통합된 자료형을 쓰기 위한 수정사항입니다.

[Feat/185] ENUM으로 자료형 통일 및 일부 테스트 코드 수정

---

src/main/java/com/gamegoo/gamegoo_v2/HomeController.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
src/main/resources/excluded-paths.yml

[Feat/201] health check API 구현

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java

[Fix/205] 중복파라미터 제거 및 호출 누락 수정

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java

[Fix/212] 회원용 게시물 조회 변수 불일치 수정

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java

[Fix/216] 게시물 상세 조회 시 티어 구분 제공

---

src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/MatchingValidator.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
src/main/java/com/gamegoo/gamegoo_v2/matching/dto/request/MatchingFoundRequest.java
src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingFoundResponse.java
src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java

[Feat/209] 매칭 found API 및 테스트 구현

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardUpdateRequest.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java

> 원하는 포지션 여러개 선택 가능
필드를 두개 wantP1, wantP2로 관리하는 방법도 있지만 유연성과 코드의 간결함을 생각해 리스트 형식으로 받아오게 했습니다.

[Feat/218] 원하는 포지션 여러개 선택 가능

---

.github/workflows/github_actions.yml
build.gradle
src/main/resources/application.yml
src/main/resources/logback-spring.xml

[Feat/223] 서버 내부 에러 발생 시 디스코드 알림 전송

---

src/main/java/com/gamegoo/gamegoo_v2/content/report/repository/ReportRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java

[Feat/232] 신고 등록 쿨타임 기능 구현

---

src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingFoundResponse.java
src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/PriorityListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java

[Fix/241] 매칭 버그 수정 

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberChampion.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/ChampionStatsResponse.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/domain/ChampionStats.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/RiotMatchResponse.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/242] Riot api에서 cs정보 받아오기

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java

[Feat/247] 최근 전적 새로고침 기능 추가

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberChampion.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java

> 회원가입 시에 뜨던 cs_perminute 필드 관련 에러 수정

[Fix/256] cs 정보 관련 에러 관련 수정

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/LoginType.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/request/RiotJoinRequest.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
src/main/resources/excluded-paths.yml
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/chat/MemberChatroomRepositoryTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java

[Feat/259] RSO 회원가입

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

[Fix/261] client_id, secret 환경 변수 추가하기 배포 해결

---

src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java

[Fix/266] rso -> riot 엔드포인트 변경

---

src/main/java/com/gamegoo/gamegoo_v2/scripts/ChampionInitializer.java
src/main/resources/static/champion_ko.json
src/test/java/com/gamegoo/gamegoo_v2/scripts/ChampionInitializerTest.java

[Feat] 챔피언 네이밍 한글 반환 로직

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java

> 챔피언 응답 필드 네이밍 수정 및 프로필 이미지 통일

[Refactor/268] 챔피언 응답 필드 네이밍 수정

---

src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotOAuthService.java

> RSO 404 에러 발생 시 redirection으로 알려주기

[Fix/273] RSO 404 에러 발생 시 redirection으로 알려주기

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardFacadeServiceTest.java

> 게시물 검색 기능 개선: 여러 포지션(주/부) 동시 필터링, Null 안전성 강화

[Feat/255] 게시물 검색 기능 개선

---

src/main/java/com/gamegoo/gamegoo_v2/content/report/controller/ReportController.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportService.java
src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java

> 신고 데이터 관리자 조회 기능 및 테스트 코드 추가

[Feat/278] 신고 데이터 확인 및 테스트 코드

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberChampion.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberChampionService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/ChampionStatsResponse.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/domain/ChampionStats.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/response/RiotMatchResponse.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

> 최근 전적 챔피언들의 kda 정보도 함께 받아와 출력합니다.

[Feat/282] kda 정보 추가 및 게시판 표기

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java

[Feat/282] 매너레벨 나의 게시판에서 확인

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/PositionRequest.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java

[Feat/280] 원하는 포지션 두 개로 하도록 변경하기

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardServiceTest.java

[Fix/288] 끌올 시간 수정 및 정렬 방식, 테스트 코드 수정

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/BanType.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/BanRequest.java
src/test/java/com/gamegoo/gamegoo_v2/external/riot/domain/ChampionStatsTest.java
src/test/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordServiceTest.java

[Fix/288] 정렬 관련 쿼리문 수정 

---

src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/CustomUserDetailsService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/chat/dto/ChatResponseFactory.java
src/main/java/com/gamegoo/gamegoo_v2/chat/dto/response/ChatMessageResponse.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/MemberValidator.java
src/main/java/com/gamegoo/gamegoo_v2/notification/dto/NotificationResponse.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/dto/BlockListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockService.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/dto/FriendInfoResponse.java
src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

> 회원 탈퇴 시 blind 필드가 변경되지 않는 문제 해결

[Fix/291] 회원 탈퇴 버그 해결

---

src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java

> SOLO 게임모드일 경우, 마스터&그랜드마스터는 끼리끼리 매칭되도록 해결

[Fix/301] SOLO 게임모드일 경우, 마스터&그랜드마스터는 서로가 매칭되도록 해결

---

src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailAsyncService.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/ChampionStatsResponse.java
src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/EmailEventListener.java
src/main/java/com/gamegoo/gamegoo_v2/game/dto/response/ChampionResponse.java
src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/295] 프로필 응답 변경 및 테스트 코드 추가

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
src/main/java/com/gamegoo/gamegoo_v2/core/batch/BatchFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/core/batch/BatchService.java
src/main/java/com/gamegoo/gamegoo_v2/core/log/DiscordLogger.java
src/main/java/com/gamegoo/gamegoo_v2/core/scheduler/MannerScheduler.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml
src/test/resources/application.yml

> 회원 매너 레벨 업데이트 스케줄러 로그 디스코드 전송
```DISCORD_SCHEDULER_WEBHOOK=aaaa```

[Feat/308] 회원 매너 레벨 업데이트 스케줄러 로그 디스코드 전송

---

src/main/java/com/gamegoo/gamegoo_v2/chat/domain/SystemMessageType.java
src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
src/main/java/com/gamegoo/gamegoo_v2/core/scheduler/SystemMessageScheduler.java
src/main/java/com/gamegoo/gamegoo_v2/core/scheduler/handler/MannerMessageHandler.java
src/main/java/com/gamegoo/gamegoo_v2/external/socket/SocketService.java
src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepository.java
src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
src/test/java/com/gamegoo/gamegoo_v2/repository/RepositoryTestSupport.java
src/test/java/com/gamegoo/gamegoo_v2/repository/matching/MatchingRecordRepositoryTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/scheduler/MannerMessageHandlerTest.java

> 매칭 성공 후 매너평가 시스템 메시지 발송 스케줄러 구현

[Feat/300] 매칭 성공 후 매너평가 시스템 메시지 발송 스케줄러 구현

---

build.gradle
src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
src/main/resources/application.yml
src/main/resources/excluded-paths.yml

[Feat/323] Prometheus 연동 설정

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardCursorResponse.java
src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardServiceTest.java

> nextCursor 필드값 추가 및 테스트 코드 추가
간단한 수정이니 바로 병합하겠습니다

[Fix/328] nextCursor 필드값 추가 및 테스트 코드 추가

---

src/main/java/com/gamegoo/gamegoo_v2/core/common/annotation/ValidCursor.java
src/main/java/com/gamegoo/gamegoo_v2/core/common/annotationValidator/ValidCursorLocalDateTimeValidator.java

> 나의 게시물에서 cursor Valid가 이상하게 되던 오류 수정

[Fix/333] 나의 게시물에서 cursor Valid가 이상하게 되던 오류 수정

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberRecentStats.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MemberRecentStatsResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRecentStatsRepository.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/ChampionStatsRefreshService.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
src/test/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MemberRecentStatsResponseTest.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

[Feat/337] 최신 통합 정보 조회 로직 반영

---

src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepository.java
src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java

[Fix/341] 회원 차단 해제 API 버그 해결

---

src/main/java/com/gamegoo/gamegoo_v2/scripts/NotificationTypeInitializer.java

> notification_type db 초기화 스크립트 추가

[Feat/344] notification_type db 초기화 스크립트 추가

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/service/BanService.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/notification/domain/NotificationTypeTitle.java
src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
src/main/java/com/gamegoo/gamegoo_v2/scripts/NotificationTypeInitializer.java
src/test/java/com/gamegoo/gamegoo_v2/TestSetup.java
src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/member/BanServiceTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/notification/NotificationServiceTest.java

> 신고 처리 완료 후 관련 당사자들에게 처리 결과를 알림으로 전송하는 기능을 구현합니다.

[Feat/350] 신고 처리 후 신고자, 피신고자에게 알림 전송 구현

---

src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
src/main/resources/excluded-paths.yml

> 비회원도 커서 기반 페이지네이션 조회가 가능하도록(모바일) 변경하였습니다.

[Fix/353] 비회원 커서 페이지네이션 위한 시큐리티 설정 수정

---

src/main/java/com/gamegoo/gamegoo_v2/core/log/DiscordLogger.java

> DiscordLogger 버그 해결
스케줄러가 정상 작동해서 제 개인 모니터링 채널로 메시지 잘 오는 것까지 확인했는데, 자꾸 디스코드 전송 실패라고 겜구 채널에 올라오고 있습니다.... 전송이 잘 되었는데도 에러 로그가 떠서 아예 로깅 안하도록 임시로 처리하겠습니다.

[Fix/358] DiscordLogger 버그 해결

---

src/main/java/com/gamegoo/gamegoo_v2/content/report/controller/ReportController.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportListResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportPageResponse.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/repository/ReportRepositoryCustom.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/repository/ReportRepositoryImpl.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportService.java
src/test/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportPageResponseTest.java
src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/report/ReportRepositoryPaginationTest.java
src/test/java/com/gamegoo/gamegoo_v2/repository/report/ReportRepositoryTest.java
src/test/java/com/gamegoo/gamegoo_v2/service/report/ReportSearchIntegrationTest.java

[Feat/370] 페이지네이션 값 반환 로직 및 테스트 코드 추가

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MemberRecentStatsResponse.java

> MemberRecents optional = false 제거로 인한 데이터 정합성 문제로 에러 발생

[Fix/372] 데이터 정합성 관련 에러 발생

---

src/main/java/com/gamegoo/gamegoo_v2/core/log/LoggingFilter.java

[Refactor/367] prometheus 관련 API 로깅 제거

---

src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java

> MemberController 코드에 프로필 이미지 수정이랑 주/부/원하는 포지션 수정 api 메소드 이름이 동일

[Fix/279] controller 변수명 중복 수정

---

src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java

[Feat/395] 20개로 수정

---

src/main/java/com/gamegoo/gamegoo_v2/HomeController.java
src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/request/RiotJoinRequest.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java

[Feat/402] 테스트 편의성 API 구현

---

src/main/resources/application.yml
src/test/resources/application.yml

> gamegoo0707 계정 2단계 인증 해제에 따른 이메일 전송용 계정 재설정

[Fix/407] 이메일 발송 계정 재설정

---

src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java

[Fix/400] 로그인 시 탈퇴 로직 추가

---

src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java

> 전적갱신 쿨타임 에러코드가 3일에 한번이라고 잘못 작성되어있어 수정

[fix/415] 전적갱신 쿨타임 에러코드 수정

---

src/main/java/com/gamegoo/gamegoo_v2/external/socket/SocketService.java
src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestFacadeServiceTest.java

[Feat/414] 친구 요청 수락 시 socket 서버 API 호출

---

src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java

> 여기에 작성해주세요.
라이엇 로그인할 때 리다이렉트 url을 프론트에서 설정할 수 있도록 추가했습니다.
기존 frontUrl 환경변수를 `/riot/callback`를 추가해서 수정해주시면 감사하겠습니다

✨[Feat] Riot OAuth 리다이렉트 url 설정 추가

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-qa.yml

[Fix/423] RSO 리다이렉트 주소 환경 변수 변경

---

src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java

> RSO 관련 메소드 불러올 당시 매개변수 설정 오류

[Fix/427] RSO 매개변수명 수정

---

src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java

> 트랜잭션 문제로 인해 RSO 회원가입 문제 수정
자꾸 수정해서 죄송합니다 ㅜㅜ

[Fix432] 트랜잭션 수정으로 인해 비동기 로직 실행 안되는 문제 

---

src/main/java/com/gamegoo/gamegoo_v2/HomeController.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/response/RiotJoinResponse.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/OAuthRedirectBuilder.java
src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java

[Feat/436] 회원가입/로그인 응답 정보 추가
